Expand 環境変数の展開
kohkubo/minishell pull request #185
Opened 2021-09-08 09:03 UTC by kohkubo

## 概要

* このプルリクの概要

環境変数展開

* 関連するIssueやプルリクエスト

close #176 

## やったこと詳細

tree_to_argv()でトークンをargvに変更する際に、minishell_expand()を呼ぶように変更。
環境変数を見つけた場合、展開する。

## やらないこと（あれば）

- $?対応
- $$対応 $が連続するケース
  - shellのプロセスIDを表示するオプションなので、$?を実装するときに合わせて実装します。
- クォート、シングルクォートの場合の展開

## 動作確認・テスト

* どのように動作確認・テストを行うか？

```
make test_issue TARGET="expand"
```

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

ft_xstrjoin()をライブラリに追加したので、今後、必要でしたら使ってください。

2021-09-08 09:42 UTC, ywake requested changes
ちゃんと見るのは明日にしますが、ちょっと見つけたので

2021-09-08 09:42 UTC, ywake commented on .gitignore
> +!*.txt
testsディレクトリのgitignoreに書かないと分離したときに問題になると思います

2021-09-08 11:22 UTC, kohkubo commented on .gitignore
> +!*.txt
訂正しました。確かにgittreeはignoreややこしいですね🍙

2021-09-09 04:20 UTC, kohkubo commented
ブランチアップデートします

2021-09-09 04:23 UTC, kohkubo commented
リベース完了しました！

2021-09-09 08:33 UTC, ywake reviewed
`minishell_expand()`の部分
コード自体がコードの流れを表すように関数をわけた書き方をするとどうなりますか？

2021-09-09 09:13 UTC, kohkubo commented
> `minishell_expand()`と`minishell_expand2()`の部分
> コード自体がコードの流れを表すように関数をわけた書き方をするとどうなりますか？

コードの見通しを改善して上げ直しました！

2021-09-09 09:51 UTC, ywake commented
めちゃくちゃ言い方を考えたんですが、僕には良い指摘の仕方とかわからなかったので、自分なりに書いてみました。
コードが流れを表すような書き方って、僕のイメージとしてはこんな感じなんですよね。

大本の関数を見れば大体の手順が載っていて、各関数の仕事は完全に分離する。関数名で仕事の内容がわかる。
https://github.com/kohkubo/minishell/blob/expand__refactored/srcs/expand/expand.c

ただこれも絶対に良いコードだとは言い張れないんで本当にどう伝えたら良いのか困ります。

2021-09-09 10:29 UTC, kohkubo commented
> 大本の関数を見れば大体の手順が載っていて、各関数の仕事は完全に分離する。関数名で仕事の内容がわかる。

この考え方は、僕も常々そうするべき、と考えているのですが、今回はseparate_to_list()の部分の実装が思いつかず現状のコードになっていました😢

可変長配列があれば、もっとコードの抽象度を上げることができるのになーというところまではたどり着いていたのですが、リストを使うアイディアを持っていませんでした。

wakeさんのコードの方が処理の流れが見やすくて、自分の書きたい流れに近かったです。
リストを使えば、クォートの部分、ダブルクォートの部分を分けてリストに格納することで展開方法を切り分けることができるので、後々の処理も書きやすく良いアルゴリズムだと思いました。

ありがとうございます😊

このリファクタのコードをベースにTODO部分等を踏まえて、再度レビューリクエストします(・∀・)

2021-09-09 10:38 UTC, ywake commented
考え方が一致していて良かったです！

そうなんですよね、多分今回のケースは一度2次元配列や今回のリストの形式にして、関数も分けておくと、クォートとか今後の処理の追加に柔軟に対応出来そうなんですよね。

色々変えてもらって構いませんので！

2021-09-12 05:15 UTC, kohkubo commented
直し終わりました。レビューお願いします。

2021-09-12 08:19 UTC, kohkubo commented
問題点を見つけたので、一旦ドラフトにします。

2021-09-12 10:19 UTC, kohkubo commented
クォートの展開の際、以下のようなケースに対応できないことがわかったので、アルゴリズムを変更し、予約文字含まずに予約文字も分割対象にしました。

アルゴリズムを改善して、このようなテストケースにも対応できるようにしました。
```
echo '$USER'"$USER"
```

アルゴリズムの検証に、クォート、ダブルクォートの実装が必要だったので、そちらの実装も行って、合わせてコミットしました。

2021-09-12 10:19 UTC, kohkubo commented
manにも追記しています。

2021-09-12 10:20 UTC, kohkubo commented
概要も追記しています。

2021-09-12 12:04 UTC, ywake requested changes
$の後ろがホワイトスペースだった時のテストが抜けていたので追加しました

2021-09-12 12:44 UTC, kohkubo commented on srcs/util.c
> +char	*wrapper_hash_getstr(t_hash_table *h, char *key)
> 前回も思ったんですがここを関数に分ける意味はなんでしょう？

最初に書いたときに頻出する処理だったので、そのときの名残でした。消去しました。

2021-09-12 12:44 UTC, kohkubo commented
レビューありがとうございます。内容を反映させたコミットをpushしました！

2021-09-12 14:44 UTC, ywake requested changes
変更ありがとうございます！（ちょっとこだわりが強すぎるかもしれないですが、こだわりたいので）
$の後ろのエラーケースをまた見つけたのでテストに追加しました。

```c
|| ((char *)separated->next->content)[0] == '\"'
```
のように$の後ろを見る条件を付け足すだけなら僕がやろうとも思ったんですが、それだけだと上手く行かないケースもあるのでちょっと複雑かもしれません。

多分現状のように配列を1文字ずつ見ていくのは分岐が複雑になるばかりなので、最初に僕が書いたように、一度変換する場所としない場所を確実に分けてから、最後に変換するほうが対応しやすいと思います.

より具体的に言うなら、`$`が来たらすぐexpand処理に走るのではなく、expandが必要な部分としてsubstring的なことをしてlistに置いておき、最後にリストを先頭から舐めて展開が必要な部分をexpandする形です。

2021-09-13 00:42 UTC, kohkubo commented
なるほど。やってみます！

2021-09-13 03:16 UTC, ywake commented on libft/libex/error.c
> +	ft_putstr_fd("libex: ", 2);
bashがエラーを出す時に
```
bash: cat: file not found
```
のようになるので、それに合わせるためにここは元々"minishell: "としていました。
"libex:"だと意味がないので消すか別の方法を使ってください

2021-09-13 03:22 UTC, kohkubo commented
アルゴリズム改善するため、一旦、ドラフトにします。

2021-09-13 03:47 UTC, kohkubo commented
```
bash-3.2$ echo $"aaa"
aaa
```

このケースはbashの統一性のない挙動だと思っていて、それに対応する必要はないという前提です。
manに記載されている実装でもないです。
zshはそのような挙動がなくなっているので、zshの展開に合わせようと思っています。

```
# zshの場合

❯ echo $"aaa" 
$aaa
```

元の$も含めて展開して、その後、stateを設定しながら、展開していくアルゴリズムだとこうなります。

```c
static t_list	*expand_env(t_list *separated)
{
	char	*content;
	char	*tmp;

	if (separated->next == NULL \
	|| ft_strchrset((char *)separated->next->content, " \t\n\v\f\r\"\'") != NULL)
		free_set(&separated->content, ft_xstrdup("$"));
	else
	{
		free_set(&separated->content, NULL);
		separated = separated->next;
		content = (char *)separated->content;
		tmp = (char *)hash_getstr(g_shell.env, content);
		if (tmp == NULL)
			tmp = "";
		free_set(&separated->content, ft_xstrdup(tmp));
	}
	return (separated);
}

static void	expand_token(t_list *separated)
{
	t_state_type	state;
	char			*content;

	state = STATE_GENERAL;
	while (separated)
	{
		content = (char *)separated->content;
		if (ft_strcmp(content, "\'") == 0 && state == STATE_GENERAL)
			free_set(&separated->content, NULL), state = STATE_IN_QUOTE;
		else if (ft_strcmp(content, "\'") == 0 && state == STATE_IN_QUOTE)
			free_set(&separated->content, NULL), state = STATE_GENERAL;
		else if (ft_strcmp(content, "\"") == 0 && state == STATE_GENERAL)
			free_set(&separated->content, NULL), state = STATE_IN_DQUOTE;
		else if (ft_strcmp(content, "\"") == 0 && state == STATE_IN_DQUOTE)
			free_set(&separated->content, NULL), state = STATE_GENERAL;
		else if (ft_strcmp(content, "$") == 0 && state != STATE_IN_QUOTE)
			separated = expand_env(separated);
		separated = separated->next;
	}
}

char	*minishell_expand(char *arg)
{
	t_list	*separated;
	char	*ret;

	if (arg == NULL)
		ft_fatal("minishell_expand : Invalid argument");
	separated = separate_to_list(arg, "\'\"\t\n\v\f\r $");
	expand_token(separated);
	ret = lst_to_string(separated);
	ft_lstclear(&separated, free);
	return (ret);
}
```

wakeさんの意見を踏まえて、クォーテーションの展開と、$の展開を独立させた書き方です。
今後、${}、$()、\`\`の展開が来ても対応しやすいアルゴリズムになっていると思います。

wakeさんの意図としては、変数展開を独立させることで、抽象度を上げようと、ということであっていますか？

話の抽象度が上がっているので、打ち合わせのときに教えてもらえれば大丈夫です！

```c
static char	*expand_env(char *arg)
{
	t_list	*list;
	t_list	*head;
	char	*tmp;

	list = separate_to_list(arg, "$ \t\n\v\f\r");
	head = list;
	while (list)
	{
		if (ft_strcmp((char *)list->content, "$") == 0 && list->next != NULL
			&& ft_strchrset((char *)list->next->content, " \t\n\v\f\r") == NULL)
		{
			free_set(&list->content, NULL);
			list = list->next;
			tmp = (char *)hash_getstr(g_shell.env, (char *)list->content);
			if (tmp == NULL)
				tmp = "";
			free_set(&list->content, ft_xstrdup(tmp));
		}
		list = list->next;
	}
	tmp = lst_to_string(head);
	ft_lstclear(&head, free);
	return (tmp);
}

static void	expand_quote(t_list *separated)
{
	t_state_type	state;
	char			*content;

	state = STATE_GENERAL;
	while (separated)
	{
		content = (char *)separated->content;
		if (ft_strcmp(content, "\'") == 0 && state == STATE_GENERAL)
			free_set(&separated->content, NULL), state = STATE_IN_QUOTE;
		else if (ft_strcmp(content, "\'") == 0 && state == STATE_IN_QUOTE)
			free_set(&separated->content, NULL), state = STATE_GENERAL;
		else if (ft_strcmp(content, "\"") == 0 && state == STATE_GENERAL)
			free_set(&separated->content, NULL), state = STATE_IN_DQUOTE;
		else if (ft_strcmp(content, "\"") == 0 && state == STATE_IN_DQUOTE)
			free_set(&separated->content, NULL), state = STATE_GENERAL;
		else if (ft_strchr(content, CHAR_DOL) != NULL
			&& state != STATE_IN_QUOTE)
			free_set(&separated->content, expand_env(content));
		separated = separated->next;
	}
}

char	*minishell_expand(char *arg)
{
	t_list	*separated;
	char	*ret;

	if (arg == NULL)
		ft_fatal("minishell_expand : Invalid argument");
	separated = separate_to_list(arg, "\'\"\t\n\v\f\r");
	expand_quote(separated);
	ret = lst_to_string(separated);
	ft_lstclear(&separated, free);
	return (ret);
}
```

2021-09-13 03:58 UTC, kohkubo commented on libft/libex/error.c
> +	ft_putstr_fd("libex: ", 2);
minishell:が出ないことが問題だとすると、xmalloc, xcallocを使っている部分もすべて変更する必要があります。

確かにzshのコードだとmalloc等もすべてwrapper関数が用意されているようです。
エラー終了する可能性のある関数をすべてラップするということでしたら、xmallocを含め、全体のリファクタリングをするべきだと思います。
ただ、そこは今回の課題の本質ではないので、xmallocで拾えるエラーに関しては、ライブラリのエラーに合わせてしまってよいという解釈をしました。

ビルトイン関数のエラーに関してはbashのエラー文言に合わせるのは課題の範囲内だと思うので、それをやるのは良いと思います！

2021-09-13 04:06 UTC, kohkubo commented on libft/libex/error.c
> +	ft_putstr_fd("libex: ", 2);
あと、ライブラリとminishellで同じ名前の関数が用意されている場合、minishellの関数が優先されるようです！

2021-09-13 04:19 UTC, ywake commented
抽象度がどうこうという抽象的な話では無くて、手順をはっきりさせ、分離させることを言っています。
expand__refactorでやっていた事です

2021-09-14 07:37 UTC, ywake reviewed
ブランチ分けるときにこちらも一緒にお願いします！

2021-09-14 07:37 UTC, ywake commented on libft/libex/error.c
> +	ft_putstr_fd("libex: ", 2);
ここなんですが、エラー文言合わせないなら5行目消しちゃえばいいかなと思いました

2021-09-16 08:43 UTC, kohkubo commented
リベース完了しました！！

2021-09-16 08:55 UTC, ywake approved these changes
OKです！お疲れ様でした！
![LGTM](https://image.lgtmoon.dev/93404)

2021-09-16 08:56 UTC, merged