libexへ関数を追加、整理
kohkubo/minishell pull request #198
Opened 2021-09-14 07:41 UTC by kohkubo

## 概要

libexへ関数を追加、整理

2021-09-14 09:34 UTC, ywake requested changes
大久保さん数行くらい読んでくれと思うかもしれませんが、ここで昔読んだプログラミングの本にあった長年忘れられない格言を一つお教えします。
```
起こりうることは起こる
```
マーフィーの法則という名前でも知られているようですが、それは知りません。

人間は機械ではないので、100%間違えないという芸当はほぼほぼ無理です。なので数行のプログラムだろうが、そこで読み間違いをするのが人間です。

もしかしたら僕の根底にあるこの観点が、まだ大久保さんにはないのかもしれないのでぜひ覚えていってください。
```
起こりうることは起こる
```
これは今後「クラスを扱う言語でなぜ変数をprivateに設定するのか」やセキュリティを考えたプログラミングをする上で必要になる観点です。

2021-09-14 09:34 UTC, ywake commented on libft/libex/separate_to_list.c
> +t_list	*separate_to_list(char *str, char *separator)
splitとも若干違うこの関数はexpand以外の利用用途が思い浮かばないのでexpand所属の関数として明示できる`srcs/expand/`配下に置くのでいいと思います。
したがってこのプルリクには含めずexpandのプルリクで行ってください

2021-09-14 10:59 UTC, kohkubo commented
レビューありがとうございます。反映してPushしました！

2021-09-14 11:05 UTC, kohkubo commented on libft/libex/separate_to_list.c
> +			buf[i] = '\0';
```c
t_list	*separate_to_lst(char *str, char *separator)
{
	t_list	*list;
	char	*start;

	list = NULL;
	while (*str != '\0')
	{
		if (ft_strchr(separator, *str) != NULL)
		{
			ft_lstadd_back(&list, ft_lstnew(ft_xsubstr(str, 0, 1)));
			str++;
		}
		else
		{
			start = str;
			while (ft_strchr(separator, *str) == NULL)
				str++;
			ft_lstadd_back(&list, ft_lstnew(ft_xsubstr(start, 0, str - start)));
		}
	}
	return (list);
}
```
なるほど、変数の数も、行数も削減できました。

2021-09-15 06:17 UTC, ywake requested changes
これ解消したらOKです！

2021-09-15 06:17 UTC, ywake commented on libft/libex/lst_to_string.c
> +char	*lst_to_string(t_list *lst)
消し忘れてます
`lst_join_str()`で代用できます

2021-09-15 06:38 UTC, kohkubo commented
すみません！対応しました！

2021-09-15 06:41 UTC, ywake approved these changes
OK!お疲れさまでした

2021-09-15 06:41 UTC, merged